// examples/vue/src/App.vue
<script setup lang="ts">
import { h, ref } from "vue";
import { defineVueColumns, indexColumn, rowActionsColumn } from "@agile-team/mach-table-vue";
import { useMachTableController } from "@agile-team/mach-table-vue/workflows";

interface Order {
  id: string;
  product: string;
  qty: number;
  price: number;
  region: string;
}

const REGIONS = ["华东", "华南", "华北", "西南", "东北"];

function makeRows(count: number): Order[] {
  return Array.from({ length: count }, (_, index) => ({
    id: `SO-${String(index + 1).padStart(6, "0")}`,
    product: `产品-${(index % 40) + 1}`,
    qty: 10 + ((index * 7) % 490),
    price: Math.round(100 + Math.random() * 9900),
    region: REGIONS[index % REGIONS.length]
  }));
}

const rows = ref(makeRows(8_000));
const controller = useMachTableController<Order>();
const persistence = { key: "vue-orders" } as const;

const columns = defineVueColumns<Order>([
  indexColumn({ headerName: "序号" }),
  { field: "id", headerName: "订单号", width: 140, pinned: "left" },
  { field: "product", headerName: "产品", flex: 1, editable: true, filter: "text" },
  { field: "qty", headerName: "数量", width: 100, filter: "number", editable: true },
  {
    field: "price",
    headerName: "单价",
    width: 120,
    filter: "number",
    type: "rightAligned",
    valueFormatter: ({ value }) => `¥${Number(value).toLocaleString()}`
  },
  {
    field: "region",
    headerName: "区域",
    width: 110,
    filter: "set",
    render: (row) => h("span", { class: "vue-region-cell" }, row.region)
  },
  rowActionsColumn<Order>({
    max: 3,
    overflow: "drawer",
    drawerTitle: "订单操作",
    onView: ({ data }) => window.alert(`查看 ${data.id}`),
    onSave: async ({ data }, changes) => {
      console.info("save", data.id, changes);
    },
    onDelete: ({ data }) => {
      rows.value = rows.value.filter((row) => row.id !== data.id);
    },
    extraActions: [
      { icon: "copy", label: "复制订单号", onClick: ({ data }) => navigator.clipboard?.writeText(data.id) },
      { icon: "download", label: "导出订单", onClick: ({ data }) => console.info("export", data.id) }
    ]
  })
]);
</script>

<template>
  <main class="demo-page">
    <h1>MachTable Vue 3 集成示例</h1>
    <MachTableToolbar
      v-model="controller.search.value"
      :api="controller.table.api.value"
      :commands="controller.commands"
      :loading="controller.busy.value"
      :selected-count="controller.selectedCount.value"
      @clear-selection="controller.table.api.value?.selection.clear()"
    >
      <button type="button" @click="rows = makeRows(rows.length + 2_000)">追加 2,000 行</button>
    </MachTableToolbar>

    <div class="demo-grid">
      <MachTable
        :ref="controller.table.ref"
        preset="crud"
        :column-defs="columns"
        :row-data="rows"
        row-key="id"
        :persistence="persistence"
      />
    </div>
  </main>
</template>

<style scoped>
.demo-page { display: grid; gap: 12px; padding: 16px; font-family: system-ui, sans-serif; }
h1 { margin: 0; font-size: 20px; }
.demo-grid { height: 70vh; min-height: 400px; }
</style>

// examples/react/src/App.tsx
import { useMemo, useState } from "react";
import {
  indexColumn,
  MachTable,
  selectionColumn,
  type CellClickEvent,
  type ColDef
} from "@agile-team/mach-table-react";
import { reactCellRenderer } from "@agile-team/mach-table-react/adapters";
import { MachTableToolbar } from "@agile-team/mach-table-react/ui";
import { useMachTableController } from "@agile-team/mach-table-react/workflows";

interface Employee {
  id: string;
  name: string;
  department: string;
  salary: number;
  level: string;
}

const DEPARTMENTS = ["研发部", "生产部", "质量部", "安全部", "市场部"];
const LEVELS = ["P4", "P5", "P6", "P7", "M1", "M2"];

function makeRows(count: number): Employee[] {
  return Array.from({ length: count }, (_, index) => ({
    id: `E${index + 1}`,
    name: `员工-${index + 1}`,
    department: DEPARTMENTS[index % DEPARTMENTS.length],
    salary: 8_000 + ((index * 137) % 22_000),
    level: LEVELS[index % LEVELS.length]
  }));
}

function SalaryCell({ value }: { value: number }) {
  const color = value > 25_000 ? "#dc2626" : value > 15_000 ? "#d97706" : "#16a34a";
  return <strong style={{ color }}>¥{value.toLocaleString()}</strong>;
}

export default function App() {
  const [rows, setRows] = useState<Employee[]>(() => makeRows(5_000));
  const [clicked, setClicked] = useState("");
  const controller = useMachTableController<Employee>();
  const columns = useMemo<ColDef<Employee>[]>(() => [
    selectionColumn({ colId: "select" }),
    indexColumn({ headerName: "序号" }),
    { field: "id", headerName: "工号", width: 110 },
    { field: "name", headerName: "姓名", flex: 1, editable: true, filter: "text" },
    { field: "department", headerName: "部门", width: 130, filter: "set" },
    { field: "salary", headerName: "薪资", width: 140, filter: "number", cellRenderer: reactCellRenderer(SalaryCell) },
    { field: "level", headerName: "职级", width: 100, editable: true, cellEditor: "select", cellEditorParams: { values: LEVELS } }
  ], []);

  return (
    <main style={{ display: "grid", gap: 12, padding: 16, fontFamily: "system-ui, sans-serif" }}>
      <h1 style={{ margin: 0, fontSize: 20 }}>MachTable React 集成示例</h1>
      <MachTableToolbar<Employee>
        api={controller.table.api}
        commands={controller.commands}
        search={controller.search}
        onSearchChange={controller.setSearch}
        loading={controller.busy}
        selectedCount={controller.selectedCount}
        onClearSelection={() => controller.table.apiRef.current?.selection.clear()}
        start={<button onClick={() => setRows(makeRows(rows.length + 1_000))}>追加 1,000 行</button>}
      />
      <div style={{ height: "70vh", minHeight: 400 }}>
        <MachTable<Employee>
          apiRef={controller.table.apiRef}
          preset="crud"
          editType="cell"
          editableIndicator="always"
          columnDefs={columns}
          rowData={rows}
          rowKey="id"
          persistence={{ key: "react-employees" }}
          onCellClicked={(event: CellClickEvent<Employee>) => setClicked(`${event.colDef.field}:${event.value}`)}
        />
      </div>
      {clicked && <small>最近点击：{clicked}</small>}
    </main>
  );
}
